### ISSUE TITLE
browser.takeSnapshot is not a function

### ISSUE THREAD

**Issue by tuan91** [webdriverio/workshop#1]
Hi i have a problem with the example test. 
Error Message: browser.takeSnapshot is not a function

If I go with the instructions from webdrivier.io, then the method "takesnapshot" works. But if I 
clone your webdriverio-hand-on the method "takesnapshot" doesnt work.
I hope you can help me.

my package.json includes this:
{
  "name": "chapter1",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "wdio wdio.local.conf.js",
    "test:sauce": "wdio wdio.sauce.conf.js"
  },
  "keywords": [],
  "author": "Christian Bromann <christian@saucelabs.com>",
  "license": "MIT",
  "devDependencies": {
    "@applitools/eyes.webdriverio": "^2.4.1",
    "@wdio/allure-reporter": "^5.7.11",
    "@wdio/applitools-service": "^5.9.3",
    "@wdio/cli": "^5.8.0",
    "@wdio/local-runner": "^5.8.0",
    "@wdio/mocha-framework": "^5.8.0",
    "@wdio/sauce-service": "^5.8.0",
    "@wdio/spec-reporter": "^5.8.0",
    "@wdio/sync": "^5.8.0",
    "allure-commandline": "^2.9.0",
    "chai": "^4.2.0",
    "chromedriver": "^74.0.0",
    "wdio-chromedriver-service": "^5.0.1",
    "webdriverio": "^5.7.15"
  }
}

**Comment by christian-bromann** [comment]
@tuan91 hey 👋 , we have updated the workshop. It should now work as expected.
