### ISSUE TITLE
Why don't you use selenium-standalone service?

### ISSUE THREAD

**Issue by mareru** [webdriverio/workshop#5]
Why don't you use selenium-standalone service to take care of the drivers and selenium server?
I see that in the first chapter you are downloading the chrome driver manually.

**Comment by christian-bromann** [comment]
Hey @mareru , thanks for filing the issue!

The intention was to start simple and have folks understand the fact that there is a driver behind every browser. Making the experience of manually downloading a driver to run it helps to understand what is going on once this process is automated. Often people don't really understand how the automation process works and I wanted to make sure this is somehow captured. The goal within the first chapters is not to build a framework, it is to play around with automation and learn about the details.

What would be your suggestion to improve this?

**Comment by mareru** [comment]
Hey @christian-bromann , thanks for fast reply.  
Yeah, I get your point and it makes total sense to me.  
Maybe you could have as part of this workshop or even another project on github which would be more advanced (meaning constructing the framework with all the fancy stuff) and there you could use also selenium-standalone service. :D

**Comment by seanpoulter** [comment]
Thanks for the suggestion @mareru. If you haven't seen it, there were some exciting driver management changes announced on [the blog](https://webdriver.io/blog/2023/07/31/driver-management/).
